In [7]:
import pandas as pd

In [13]:
df = pd.read_csv('personality_dataset.csv')
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert
...,...,...,...,...,...,...,...,...
2895,3.0,No,7.0,6.0,No,6.0,6.0,Extrovert
2896,3.0,No,8.0,3.0,No,14.0,9.0,Extrovert
2897,4.0,Yes,1.0,1.0,Yes,4.0,0.0,Introvert
2898,11.0,Yes,1.0,NaN,Yes,2.0,0.0,Introvert
2899,3.0,No,6.0,6.0,No,6.0,9.0,Extrovert

<h2>Skenario dan data yg dapat dianalisis dari dataset tersebut</h2>
<table border="1" class="table table-bordered">
  <thead>
    <tr>
      <th>No.</th>
      <th>Pertanyaan / Insight</th>
      <th>Variabel yang Dianalisis</th>
      <th>Tujuan Analisis</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Hubungan antara waktu sendiri dan kepribadian</td>
      <td>Time_spent_Alone, Personality</td>
      <td>Menilai apakah lebih banyak waktu sendiri menunjukkan kecenderungan introvert</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Pengaruh kelelahan sosial terhadap kepribadian</td>
      <td>Drained_after_socializing, Personality</td>
      <td>Apakah individu yang merasa lelah setelah sosialisasi cenderung introvert</td>
    </tr>
    <tr>
      <td>3</td>
      <td>Aktivitas sosial dan frekuensi posting</td>
      <td>Social_event_attendance, Post_frequency, Personality</td>
      <td>Mengetahui apakah extrovert lebih aktif di dunia nyata maupun media sosial</td>
    </tr>
    <tr>
      <td>4</td>
      <td>Ukuran lingkaran pertemanan terhadap kepribadian</td>
      <td>Friends_circle_size, Personality</td>
      <td>Membedakan jaringan sosial antara introvert dan extrovert</td>
    </tr>
  </tbody>
</table>